-- ==============================================================
-- AI INTERVIEWER PLATFORM — Complete Database Setup
-- ==============================================================
-- Run this entire script once in your Supabase SQL Editor.
-- This is the consolidated form of all 23 individual migrations.
-- Last updated: Migration 023
-- ==============================================================

-- ==============================================================
-- EXTENSIONS
-- ==============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================
-- HELPER FUNCTIONS
-- ==============================================================

-- Returns true if the calling JWT belongs to an HR role.
-- Used by DELETE policies so we don't repeat the COALESCE everywhere.
CREATE OR REPLACE FUNCTION public.is_hr()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COALESCE(
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'role',
    ''
  ) IN ('hr_admin', 'hr_recruiter', 'system');
$$;

-- Trigger function that keeps updated_at fresh on every row update.
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==============================================================
-- CORE TABLES
-- ==============================================================

-- ── Candidates ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS candidates_ai_interview (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id   TEXT UNIQUE,
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  phone         TEXT,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now(),
  metadata      JSONB DEFAULT '{}'::jsonb
);

CREATE TRIGGER set_candidates_updated_at
  BEFORE UPDATE ON candidates_ai_interview
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ── Job Descriptions ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS job_descriptions_ai_interview (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id            UUID REFERENCES candidates_ai_interview(id) ON DELETE CASCADE,
  raw_text                TEXT NOT NULL,
  job_name                TEXT,                          -- human-readable role/position name
  parsed_skills           TEXT[] DEFAULT '{}',
  parsed_years_experience DECIMAL(4,1),
  parsed_roles            TEXT[] DEFAULT '{}',
  created_at              TIMESTAMPTZ DEFAULT now()
);

-- ── Resumes ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS resumes_ai_interview (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id       UUID REFERENCES candidates_ai_interview(id) ON DELETE CASCADE,
  raw_text           TEXT NOT NULL,
  file_url           TEXT,
  parsed_skills      TEXT[] DEFAULT '{}',
  parsed_experience  JSONB DEFAULT '[]'::jsonb,
  parsed_education   JSONB DEFAULT '[]'::jsonb,
  created_at         TIMESTAMPTZ DEFAULT now()
);

-- ── Interview Sessions ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS interview_sessions_ai_interview (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id  UUID REFERENCES candidates_ai_interview(id) ON DELETE CASCADE,
  jd_id         UUID REFERENCES job_descriptions_ai_interview(id),
  resume_id     UUID REFERENCES resumes_ai_interview(id),
  status        TEXT DEFAULT 'pending'
                  CHECK (status IN ('pending','invited','in_progress',
                                    'completed','expired','cancelled','flagged')),
  invite_link   TEXT UNIQUE,
  token_hash    TEXT,
  expires_at    TIMESTAMPTZ NOT NULL,
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ,
  created_by    UUID,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TRIGGER set_sessions_updated_at
  BEFORE UPDATE ON interview_sessions_ai_interview
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ── Interview Blueprints ──────────────────────────────────────
-- Durable structured interview plan generated by n8n before the session starts.
CREATE TABLE IF NOT EXISTS interview_blueprints_ai_interview (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       UUID NOT NULL UNIQUE
                     REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE,
  version          TEXT NOT NULL DEFAULT 'v1',
  competencies     JSONB NOT NULL DEFAULT '[]'::jsonb,
  question_plan    JSONB NOT NULL DEFAULT '[]'::jsonb,
  candidate_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  constraints      JSONB NOT NULL DEFAULT '{"max_primary_questions":10,"max_follow_ups_per_question":1}'::jsonb,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Interview Questions ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS interview_questions_ai_interview (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id           UUID REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE,
  question_text        TEXT NOT NULL,
  question_type        TEXT DEFAULT 'technical'
                         CHECK (question_type IN ('technical','behavioral','situational','cultural')),
  source               TEXT DEFAULT 'ai_generated',
  order_index          INT NOT NULL,
  parent_question_id   UUID REFERENCES interview_questions_ai_interview(id),
  plan_item_id         TEXT,
  competency_ids       JSONB NOT NULL DEFAULT '[]'::jsonb,
  decision_rationale   TEXT,
  -- Why a follow-up question was inserted (NULL for primary questions).
  insufficiency_reason TEXT CHECK (insufficiency_reason IN ('lacks_depth','lacks_evidence','vague','irrelevant')),
  created_at           TIMESTAMPTZ DEFAULT now()
);

COMMENT ON COLUMN interview_questions_ai_interview.insufficiency_reason IS
  'For follow-up questions: the failure mode detected in the parent answer that triggered this follow-up. NULL for primary questions.';

-- ── Interview Answers ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS interview_answers_ai_interview (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id    UUID REFERENCES interview_questions_ai_interview(id) ON DELETE CASCADE,
  session_id     UUID REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE,
  answer_text    TEXT,
  audio_url      TEXT,
  duration_secs  INT,
  ai_live_note   JSONB,    -- live per-answer assessment from analyzeAnswerInRealtime
  ai_assessment  JSONB,    -- extended assessment data
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ── Scorecards ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scorecards_ai_interview (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id            UUID REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE UNIQUE,
  technical_score       DECIMAL(5,2) CHECK (technical_score BETWEEN 0 AND 100),
  communication_score   DECIMAL(5,2) CHECK (communication_score BETWEEN 0 AND 100),
  problem_solving_score DECIMAL(5,2) CHECK (problem_solving_score BETWEEN 0 AND 100),
  cultural_fit_score    DECIMAL(5,2) CHECK (cultural_fit_score BETWEEN 0 AND 100),
  overall_score         DECIMAL(5,2) CHECK (overall_score BETWEEN 0 AND 100),
  authenticity_score    DECIMAL(5,2) CHECK (authenticity_score BETWEEN 0 AND 100),
  red_flag_count        INTEGER DEFAULT 0,
  red_flags             TEXT[] DEFAULT '{}',
  resume_vs_reality     JSONB DEFAULT '[]'::jsonb,
  strengths             TEXT[] DEFAULT '{}',
  weaknesses            TEXT[] DEFAULT '{}',
  recommendation        TEXT CHECK (recommendation IN ('strong_hire','hire','consider','no_go')),
  ai_rationale          TEXT,
  detailed_rationale    TEXT,
  live_notes            JSONB DEFAULT '[]'::jsonb,
  scoring_model_version TEXT,
  evaluated_at          TIMESTAMPTZ DEFAULT now(),
  reviewed_by_human     BOOLEAN DEFAULT FALSE,
  created_at            TIMESTAMPTZ DEFAULT now()
);

-- ── Proctoring Events ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS proctoring_events_ai_interview (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  UUID REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE,
  event_type  TEXT NOT NULL
                CHECK (event_type IN ('tab_switch','window_blur','browser_resize',
                                      'face_absent','face_multiple','face_mismatch',
                                      'audio_silence','audio_level','copy_paste',
                                      'keyboard_shortcut','fullscreen_exit')),
  severity    TEXT DEFAULT 'warning'
                CHECK (severity IN ('info','warning','critical')),
  timestamp   TIMESTAMPTZ DEFAULT now(),
  payload     JSONB DEFAULT '{}'::jsonb
);

-- ── Recordings ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS recordings_ai_interview (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       UUID REFERENCES interview_sessions_ai_interview(id) ON DELETE CASCADE,
  stream_type      TEXT NOT NULL
                     CHECK (stream_type IN ('camera_video','screen_video','audio_mixed')),
  status           TEXT DEFAULT 'processing'
                     CHECK (status IN ('processing','ready','archived','failed')),
  storage_path     TEXT NOT NULL,
  duration_secs    INT,
  file_size_bytes  BIGINT,
  mime_type        TEXT,
  transcoded_paths JSONB DEFAULT '{}'::jsonb,
  created_at       TIMESTAMPTZ DEFAULT now()
);

-- ── Audit Log ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log_ai_interview (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_type    TEXT NOT NULL CHECK (actor_type IN ('system','hr_user','candidate','api')),
  actor_id      TEXT,
  action        TEXT NOT NULL,
  resource_type TEXT,
  resource_id   TEXT,
  details       JSONB DEFAULT '{}'::jsonb,
  ip_address    TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================
-- INDEXES
-- ==============================================================

CREATE INDEX IF NOT EXISTS idx_sessions_status     ON interview_sessions_ai_interview(status);
CREATE INDEX IF NOT EXISTS idx_sessions_candidate  ON interview_sessions_ai_interview(candidate_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires    ON interview_sessions_ai_interview(expires_at);
CREATE INDEX IF NOT EXISTS idx_questions_session   ON interview_questions_ai_interview(session_id, order_index);
CREATE INDEX IF NOT EXISTS idx_questions_parent    ON interview_questions_ai_interview(parent_question_id);
CREATE INDEX IF NOT EXISTS idx_answers_session     ON interview_answers_ai_interview(session_id);
CREATE INDEX IF NOT EXISTS idx_blueprints_session  ON interview_blueprints_ai_interview(session_id);
CREATE INDEX IF NOT EXISTS idx_scorecards_session  ON scorecards_ai_interview(session_id);
CREATE INDEX IF NOT EXISTS idx_proctoring_session  ON proctoring_events_ai_interview(session_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_proctoring_severity ON proctoring_events_ai_interview(session_id, severity);
CREATE INDEX IF NOT EXISTS idx_candidates_email    ON candidates_ai_interview(email);
CREATE INDEX IF NOT EXISTS idx_audit_created       ON audit_log_ai_interview(created_at DESC);

-- ==============================================================
-- STORAGE BUCKET
-- ==============================================================
-- Public bucket, no per-object size cap (governed by Supabase plan),
-- no MIME type restriction (simplifies TUS multipart uploads).

INSERT INTO storage.buckets (id, name, public, avif_autodetection, file_size_limit, allowed_mime_types)
VALUES ('recordings', 'recordings', true, false, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  public             = true,
  file_size_limit    = NULL,
  allowed_mime_types = NULL;

-- ==============================================================
-- ROW LEVEL SECURITY — Enable
-- ==============================================================

ALTER TABLE candidates_ai_interview          ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_descriptions_ai_interview    ENABLE ROW LEVEL SECURITY;
ALTER TABLE resumes_ai_interview             ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_sessions_ai_interview  ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_blueprints_ai_interview ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_questions_ai_interview ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_answers_ai_interview   ENABLE ROW LEVEL SECURITY;
ALTER TABLE scorecards_ai_interview          ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctoring_events_ai_interview   ENABLE ROW LEVEL SECURITY;
ALTER TABLE recordings_ai_interview          ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log_ai_interview           ENABLE ROW LEVEL SECURITY;

-- ==============================================================
-- RLS POLICIES — Candidates
-- ==============================================================

-- HR: read
DROP POLICY IF EXISTS hr_select_candidates ON candidates_ai_interview;
CREATE POLICY hr_select_candidates ON candidates_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

-- HR: insert
DROP POLICY IF EXISTS hr_insert_candidates ON candidates_ai_interview;
CREATE POLICY hr_insert_candidates ON candidates_ai_interview FOR INSERT
  WITH CHECK (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
                IN ('hr_admin', 'hr_recruiter', 'system'));

-- HR: update
DROP POLICY IF EXISTS hr_update_candidates ON candidates_ai_interview;
CREATE POLICY hr_update_candidates ON candidates_ai_interview FOR UPDATE
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'system'));

-- HR: delete (CASCADE source)
DROP POLICY IF EXISTS hr_delete_candidates ON candidates_ai_interview;
CREATE POLICY hr_delete_candidates ON candidates_ai_interview FOR DELETE
  USING (public.is_hr());

-- Candidate: read their own record via active session
DROP POLICY IF EXISTS candidate_select_own_candidate_record ON candidates_ai_interview;
CREATE POLICY candidate_select_own_candidate_record ON candidates_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.candidate_id = candidates_ai_interview.id
      AND s.status IN ('invited', 'in_progress', 'completed')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Job Descriptions
-- ==============================================================

DROP POLICY IF EXISTS hr_select_jd ON job_descriptions_ai_interview;
CREATE POLICY hr_select_jd ON job_descriptions_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_insert_jd ON job_descriptions_ai_interview;
CREATE POLICY hr_insert_jd ON job_descriptions_ai_interview FOR INSERT
  WITH CHECK (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
                IN ('hr_admin', 'hr_recruiter', 'system'));

DROP POLICY IF EXISTS hr_delete_job_descriptions ON job_descriptions_ai_interview;
CREATE POLICY hr_delete_job_descriptions ON job_descriptions_ai_interview FOR DELETE
  USING (public.is_hr());

DROP POLICY IF EXISTS candidate_select_jd ON job_descriptions_ai_interview;
CREATE POLICY candidate_select_jd ON job_descriptions_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.jd_id = job_descriptions_ai_interview.id
      AND s.status IN ('invited', 'in_progress', 'completed')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Resumes
-- ==============================================================

DROP POLICY IF EXISTS hr_select_resumes ON resumes_ai_interview;
CREATE POLICY hr_select_resumes ON resumes_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_insert_resumes ON resumes_ai_interview;
CREATE POLICY hr_insert_resumes ON resumes_ai_interview FOR INSERT
  WITH CHECK (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
                IN ('hr_admin', 'hr_recruiter', 'system'));

DROP POLICY IF EXISTS hr_delete_resumes ON resumes_ai_interview;
CREATE POLICY hr_delete_resumes ON resumes_ai_interview FOR DELETE
  USING (public.is_hr());

DROP POLICY IF EXISTS candidate_select_resumes ON resumes_ai_interview;
CREATE POLICY candidate_select_resumes ON resumes_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.resume_id = resumes_ai_interview.id
      AND s.status IN ('invited', 'in_progress', 'completed')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Interview Sessions
-- ==============================================================

-- HR: read / insert / update / delete
DROP POLICY IF EXISTS hr_select_sessions ON interview_sessions_ai_interview;
CREATE POLICY hr_select_sessions ON interview_sessions_ai_interview FOR SELECT
  USING (auth.jwt() ->> 'role' IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_insert_sessions ON interview_sessions_ai_interview;
CREATE POLICY hr_insert_sessions ON interview_sessions_ai_interview FOR INSERT
  WITH CHECK (auth.jwt() ->> 'role' IN ('hr_admin', 'hr_recruiter', 'system'));

DROP POLICY IF EXISTS hr_update_sessions ON interview_sessions_ai_interview;
CREATE POLICY hr_update_sessions ON interview_sessions_ai_interview FOR UPDATE
  USING (auth.jwt() ->> 'role' IN ('hr_admin', 'system'));

DROP POLICY IF EXISTS hr_delete_sessions ON interview_sessions_ai_interview;
CREATE POLICY hr_delete_sessions ON interview_sessions_ai_interview FOR DELETE
  USING (public.is_hr());

-- Candidate: read active session
DROP POLICY IF EXISTS candidate_select_active_session ON interview_sessions_ai_interview;
CREATE POLICY candidate_select_active_session ON interview_sessions_ai_interview FOR SELECT
  USING (
    status IN ('invited', 'in_progress', 'completed')
    AND expires_at > now()
  );

-- Candidate: update status (invited/in_progress → in_progress/completed)
DROP POLICY IF EXISTS candidate_update_active_session_status ON interview_sessions_ai_interview;
CREATE POLICY candidate_update_active_session_status ON interview_sessions_ai_interview FOR UPDATE
  USING (status IN ('invited', 'in_progress') AND expires_at > now())
  WITH CHECK (status IN ('in_progress', 'completed'));

-- ==============================================================
-- RLS POLICIES — Interview Blueprints
-- ==============================================================

DROP POLICY IF EXISTS candidate_select_interview_blueprint ON interview_blueprints_ai_interview;
CREATE POLICY candidate_select_interview_blueprint ON interview_blueprints_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_blueprints_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

DROP POLICY IF EXISTS candidate_insert_interview_blueprint ON interview_blueprints_ai_interview;
CREATE POLICY candidate_insert_interview_blueprint ON interview_blueprints_ai_interview FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_blueprints_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

DROP POLICY IF EXISTS candidate_update_interview_blueprint ON interview_blueprints_ai_interview;
CREATE POLICY candidate_update_interview_blueprint ON interview_blueprints_ai_interview FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_blueprints_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Interview Questions
-- ==============================================================

-- HR
DROP POLICY IF EXISTS hr_select_questions ON interview_questions_ai_interview;
CREATE POLICY hr_select_questions ON interview_questions_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_delete_questions ON interview_questions_ai_interview;
CREATE POLICY hr_delete_questions ON interview_questions_ai_interview FOR DELETE
  USING (public.is_hr());

-- Candidate: read questions for their session
DROP POLICY IF EXISTS candidate_select_session_questions ON interview_questions_ai_interview;
CREATE POLICY candidate_select_session_questions ON interview_questions_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_questions_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress', 'completed')
      AND s.expires_at > now()
  ));

-- Candidate: insert dynamic / follow-up questions
DROP POLICY IF EXISTS candidate_insert_session_questions ON interview_questions_ai_interview;
CREATE POLICY candidate_insert_session_questions ON interview_questions_ai_interview FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_questions_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- Candidate: delete questions (e.g. clearing pre-generated queue at start)
DROP POLICY IF EXISTS candidate_delete_session_questions ON interview_questions_ai_interview;
CREATE POLICY candidate_delete_session_questions ON interview_questions_ai_interview FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_questions_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- Candidate: update question order_index (needed when inserting follow-ups)
DROP POLICY IF EXISTS candidate_update_session_questions ON interview_questions_ai_interview;
CREATE POLICY candidate_update_session_questions ON interview_questions_ai_interview FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_questions_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Interview Answers
-- ==============================================================

-- HR
DROP POLICY IF EXISTS hr_select_answers ON interview_answers_ai_interview;
CREATE POLICY hr_select_answers ON interview_answers_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_delete_answers ON interview_answers_ai_interview;
CREATE POLICY hr_delete_answers ON interview_answers_ai_interview FOR DELETE
  USING (public.is_hr());

-- Candidate: insert answers during active session
DROP POLICY IF EXISTS candidate_insert_session_answers ON interview_answers_ai_interview;
CREATE POLICY candidate_insert_session_answers ON interview_answers_ai_interview FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_answers_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- Candidate: read own answers
DROP POLICY IF EXISTS candidate_select_session_answers ON interview_answers_ai_interview;
CREATE POLICY candidate_select_session_answers ON interview_answers_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_answers_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress', 'completed')
      AND s.expires_at > now()
  ));

-- Candidate: update answers (to attach ai_live_note)
DROP POLICY IF EXISTS candidate_update_session_answers ON interview_answers_ai_interview;
CREATE POLICY candidate_update_session_answers ON interview_answers_ai_interview FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = interview_answers_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- ==============================================================
-- RLS POLICIES — Scorecards
-- ==============================================================

DROP POLICY IF EXISTS hr_select_scorecards ON scorecards_ai_interview;
CREATE POLICY hr_select_scorecards ON scorecards_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system'));

DROP POLICY IF EXISTS hr_update_scorecards ON scorecards_ai_interview;
CREATE POLICY hr_update_scorecards ON scorecards_ai_interview FOR UPDATE
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'system'));

DROP POLICY IF EXISTS hr_delete_scorecards ON scorecards_ai_interview;
CREATE POLICY hr_delete_scorecards ON scorecards_ai_interview FOR DELETE
  USING (public.is_hr());

-- ==============================================================
-- RLS POLICIES — Proctoring Events
-- ==============================================================

-- Candidate: insert proctoring events during active session
DROP POLICY IF EXISTS candidate_insert_proctoring_events ON proctoring_events_ai_interview;
CREATE POLICY candidate_insert_proctoring_events ON proctoring_events_ai_interview FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = proctoring_events_ai_interview.session_id
      AND s.status IN ('invited', 'in_progress')
      AND s.expires_at > now()
  ));

-- Candidate: read own proctoring events
DROP POLICY IF EXISTS candidate_select_proctoring_events ON proctoring_events_ai_interview;
CREATE POLICY candidate_select_proctoring_events ON proctoring_events_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = proctoring_events_ai_interview.session_id
      AND s.expires_at > now()
  ));

-- HR: read proctoring events
DROP POLICY IF EXISTS hr_select_proctoring ON proctoring_events_ai_interview;
CREATE POLICY hr_select_proctoring ON proctoring_events_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'hr_recruiter', 'system'));

DROP POLICY IF EXISTS hr_delete_proctoring_events ON proctoring_events_ai_interview;
CREATE POLICY hr_delete_proctoring_events ON proctoring_events_ai_interview FOR DELETE
  USING (public.is_hr());

-- ==============================================================
-- RLS POLICIES — Recordings (table)
-- ==============================================================

-- Candidate: insert recording metadata for active session
DROP POLICY IF EXISTS candidate_insert_recordings_table ON recordings_ai_interview;
CREATE POLICY candidate_insert_recordings_table ON recordings_ai_interview FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = recordings_ai_interview.session_id
      AND s.status IN ('pending', 'invited', 'in_progress', 'completed')
  ));

-- Candidate: update recording metadata (finalize after interview ends)
DROP POLICY IF EXISTS candidate_update_recordings ON recordings_ai_interview;
CREATE POLICY candidate_update_recordings ON recordings_ai_interview FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = recordings_ai_interview.session_id
      AND s.status IN ('pending', 'invited', 'in_progress', 'completed')
  ));

-- Candidate: read own recordings
DROP POLICY IF EXISTS candidate_select_own_recordings ON recordings_ai_interview;
CREATE POLICY candidate_select_own_recordings ON recordings_ai_interview FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM interview_sessions_ai_interview s
    WHERE s.id = recordings_ai_interview.session_id
      AND s.status IN ('pending', 'invited', 'in_progress', 'completed')
  ));

-- HR: full access to recordings
DROP POLICY IF EXISTS hr_select_recordings ON recordings_ai_interview;
CREATE POLICY hr_select_recordings ON recordings_ai_interview FOR ALL
  USING (true);

DROP POLICY IF EXISTS hr_delete_recordings ON recordings_ai_interview;
CREATE POLICY hr_delete_recordings ON recordings_ai_interview FOR DELETE
  USING (public.is_hr());

-- ==============================================================
-- RLS POLICIES — Storage (recordings bucket)
-- ==============================================================

-- Anyone can insert objects into the recordings bucket (candidate upload)
DROP POLICY IF EXISTS candidate_insert_recordings ON storage.objects;
CREATE POLICY candidate_insert_recordings ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'recordings');

-- Anyone can read objects from the recordings bucket (public bucket + signed URL fallback)
DROP POLICY IF EXISTS candidate_select_recordings_storage ON storage.objects;
CREATE POLICY candidate_select_recordings_storage ON storage.objects FOR SELECT
  USING (bucket_id = 'recordings');

-- HR: also covered by the permissive SELECT above; explicit policy for clarity
DROP POLICY IF EXISTS hr_select_recordings_storage ON storage.objects;
CREATE POLICY hr_select_recordings_storage ON storage.objects FOR SELECT
  USING (
    bucket_id = 'recordings'
    AND COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
          IN ('hr_admin', 'hr_recruiter', 'hr_viewer', 'system')
  );

-- ==============================================================
-- RLS POLICIES — Audit Log
-- ==============================================================

DROP POLICY IF EXISTS hr_select_audit ON audit_log_ai_interview;
CREATE POLICY hr_select_audit ON audit_log_ai_interview FOR SELECT
  USING (COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role', '')
           IN ('hr_admin', 'system'));

-- ==============================================================
-- HELPER FUNCTION — get_sessions_with_candidates
-- ==============================================================
-- HR read sessions with full candidate data, bypassing candidate RLS
-- via SECURITY DEFINER so the function runs as table owner.

CREATE OR REPLACE FUNCTION get_sessions_with_candidates()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result JSON;
BEGIN
  SELECT json_agg(
    json_build_object(
      'id',            s.id,
      'candidate_id',  s.candidate_id,
      'jd_id',         s.jd_id,
      'resume_id',     s.resume_id,
      'status',        s.status,
      'invite_link',   s.invite_link,
      'token_hash',    s.token_hash,
      'expires_at',    s.expires_at,
      'started_at',    s.started_at,
      'completed_at',  s.completed_at,
      'created_by',    s.created_by,
      'created_at',    s.created_at,
      'updated_at',    s.updated_at,
      'candidates',    CASE WHEN c.id IS NOT NULL THEN
        json_build_object(
          'id',           c.id,
          'external_id',  c.external_id,
          'name',         c.name,
          'email',        c.email,
          'phone',        c.phone,
          'created_at',   c.created_at,
          'updated_at',   c.updated_at,
          'metadata',     c.metadata
        )
      ELSE NULL END
    )
    ORDER BY s.created_at DESC
  ) INTO result
  FROM interview_sessions_ai_interview s
  LEFT JOIN candidates_ai_interview c ON c.id = s.candidate_id;

  RETURN COALESCE(result, '[]'::json);
END;
$$;

GRANT EXECUTE ON FUNCTION get_sessions_with_candidates TO anon;
GRANT EXECUTE ON FUNCTION get_sessions_with_candidates TO authenticated;

-- ==============================================================
-- REALTIME
-- ==============================================================
-- Enable Supabase Realtime for tables the frontend subscribes to.

ALTER PUBLICATION supabase_realtime ADD TABLE interview_sessions_ai_interview;
ALTER PUBLICATION supabase_realtime ADD TABLE scorecards_ai_interview;
ALTER PUBLICATION supabase_realtime ADD TABLE proctoring_events_ai_interview;
